// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as schedule_GET } from '../_routes/schedule/route.ts'

export const handle = createRouter('schedule', [
  { method: 'GET', pattern: '/schedule', handler: schedule_GET },
])
