// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PUT as divisions__id_PUT, DELETE as divisions__id_DELETE } from '../_routes/divisions/[id]/route.ts'
import { GET as divisions_GET, POST as divisions_POST } from '../_routes/divisions/route.ts'

export const handle = createRouter('divisions', [
  { method: 'PUT', pattern: '/divisions/:id', handler: divisions__id_PUT },
  { method: 'DELETE', pattern: '/divisions/:id', handler: divisions__id_DELETE },
  { method: 'GET', pattern: '/divisions', handler: divisions_GET },
  { method: 'POST', pattern: '/divisions', handler: divisions_POST },
])
