// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as leaderboard_GET } from '../_routes/leaderboard/route.ts'

export const handle = createRouter('leaderboard', [
  { method: 'GET', pattern: '/leaderboard', handler: leaderboard_GET },
])
