// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PUT as athletes__id_PUT, DELETE as athletes__id_DELETE } from '../_routes/athletes/[id]/route.ts'
import { POST as athletes__id_swap_POST } from '../_routes/athletes/[id]/swap/route.ts'
import { POST as athletes__id_withdraw_POST, DELETE as athletes__id_withdraw_DELETE } from '../_routes/athletes/[id]/withdraw/route.ts'
import { GET as athletes_GET, POST as athletes_POST, DELETE as athletes_DELETE } from '../_routes/athletes/route.ts'

export const handle = createRouter('athletes', [
  { method: 'PUT', pattern: '/athletes/:id', handler: athletes__id_PUT },
  { method: 'DELETE', pattern: '/athletes/:id', handler: athletes__id_DELETE },
  { method: 'POST', pattern: '/athletes/:id/swap', handler: athletes__id_swap_POST },
  { method: 'POST', pattern: '/athletes/:id/withdraw', handler: athletes__id_withdraw_POST },
  { method: 'DELETE', pattern: '/athletes/:id/withdraw', handler: athletes__id_withdraw_DELETE },
  { method: 'GET', pattern: '/athletes', handler: athletes_GET },
  { method: 'POST', pattern: '/athletes', handler: athletes_POST },
  { method: 'DELETE', pattern: '/athletes', handler: athletes_DELETE },
])
