// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PUT as workouts__id_assignments_reorder_PUT } from '../_routes/workouts/[id]/assignments/reorder/route.ts'
import { GET as workouts__id_assignments_GET, POST as workouts__id_assignments_POST } from '../_routes/workouts/[id]/assignments/route.ts'
import { POST as workouts__id_calculate_POST } from '../_routes/workouts/[id]/calculate/route.ts'
import { DELETE as workouts__id_equipment__equipmentId_DELETE } from '../_routes/workouts/[id]/equipment/[equipmentId]/route.ts'
import { GET as workouts__id_equipment_GET, POST as workouts__id_equipment_POST } from '../_routes/workouts/[id]/equipment/route.ts'
import { PUT as workouts__id_heat_times_PUT } from '../_routes/workouts/[id]/heat-times/route.ts'
import { POST as workouts__id_heats__heatNum_complete_POST, DELETE as workouts__id_heats__heatNum_complete_DELETE } from '../_routes/workouts/[id]/heats/[heatNum]/complete/route.ts'
import { POST as workouts__id_judge_assignments_generate_POST } from '../_routes/workouts/[id]/judge-assignments/generate/route.ts'
import { GET as workouts__id_judge_assignments_GET, POST as workouts__id_judge_assignments_POST, DELETE as workouts__id_judge_assignments_DELETE } from '../_routes/workouts/[id]/judge-assignments/route.ts'
import { POST as workouts__id_reset_POST } from '../_routes/workouts/[id]/reset/route.ts'
import { GET as workouts__id_GET, PUT as workouts__id_PUT, DELETE as workouts__id_DELETE } from '../_routes/workouts/[id]/route.ts'
import { GET as workouts__id_scores_GET, POST as workouts__id_scores_POST, PATCH as workouts__id_scores_PATCH, DELETE as workouts__id_scores_DELETE } from '../_routes/workouts/[id]/scores/route.ts'
import { GET as workouts_GET, POST as workouts_POST } from '../_routes/workouts/route.ts'

export const handle = createRouter('workouts', [
  { method: 'PUT', pattern: '/workouts/:id/assignments/reorder', handler: workouts__id_assignments_reorder_PUT },
  { method: 'GET', pattern: '/workouts/:id/assignments', handler: workouts__id_assignments_GET },
  { method: 'POST', pattern: '/workouts/:id/assignments', handler: workouts__id_assignments_POST },
  { method: 'POST', pattern: '/workouts/:id/calculate', handler: workouts__id_calculate_POST },
  { method: 'DELETE', pattern: '/workouts/:id/equipment/:equipmentId', handler: workouts__id_equipment__equipmentId_DELETE },
  { method: 'GET', pattern: '/workouts/:id/equipment', handler: workouts__id_equipment_GET },
  { method: 'POST', pattern: '/workouts/:id/equipment', handler: workouts__id_equipment_POST },
  { method: 'PUT', pattern: '/workouts/:id/heat-times', handler: workouts__id_heat_times_PUT },
  { method: 'POST', pattern: '/workouts/:id/heats/:heatNum/complete', handler: workouts__id_heats__heatNum_complete_POST },
  { method: 'DELETE', pattern: '/workouts/:id/heats/:heatNum/complete', handler: workouts__id_heats__heatNum_complete_DELETE },
  { method: 'POST', pattern: '/workouts/:id/judge-assignments/generate', handler: workouts__id_judge_assignments_generate_POST },
  { method: 'GET', pattern: '/workouts/:id/judge-assignments', handler: workouts__id_judge_assignments_GET },
  { method: 'POST', pattern: '/workouts/:id/judge-assignments', handler: workouts__id_judge_assignments_POST },
  { method: 'DELETE', pattern: '/workouts/:id/judge-assignments', handler: workouts__id_judge_assignments_DELETE },
  { method: 'POST', pattern: '/workouts/:id/reset', handler: workouts__id_reset_POST },
  { method: 'GET', pattern: '/workouts/:id', handler: workouts__id_GET },
  { method: 'PUT', pattern: '/workouts/:id', handler: workouts__id_PUT },
  { method: 'DELETE', pattern: '/workouts/:id', handler: workouts__id_DELETE },
  { method: 'GET', pattern: '/workouts/:id/scores', handler: workouts__id_scores_GET },
  { method: 'POST', pattern: '/workouts/:id/scores', handler: workouts__id_scores_POST },
  { method: 'PATCH', pattern: '/workouts/:id/scores', handler: workouts__id_scores_PATCH },
  { method: 'DELETE', pattern: '/workouts/:id/scores', handler: workouts__id_scores_DELETE },
  { method: 'GET', pattern: '/workouts', handler: workouts_GET },
  { method: 'POST', pattern: '/workouts', handler: workouts_POST },
])
