// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PATCH as comp_users__userId_PATCH, DELETE as comp_users__userId_DELETE } from '../_routes/comp-users/[userId]/route.ts'
import { GET as comp_users_GET, POST as comp_users_POST } from '../_routes/comp-users/route.ts'

export const handle = createRouter('comp-users', [
  { method: 'PATCH', pattern: '/comp-users/:userId', handler: comp_users__userId_PATCH },
  { method: 'DELETE', pattern: '/comp-users/:userId', handler: comp_users__userId_DELETE },
  { method: 'GET', pattern: '/comp-users', handler: comp_users_GET },
  { method: 'POST', pattern: '/comp-users', handler: comp_users_POST },
])
