// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as ops_GET } from '../_routes/ops/route.ts'

export const handle = createRouter('ops', [
  { method: 'GET', pattern: '/ops', handler: ops_GET },
])
