// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as me_GET } from '../_routes/me/route.ts'

export const handle = createRouter('me', [
  { method: 'GET', pattern: '/me', handler: me_GET },
])
