// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PUT as workout_locations__id_PUT, DELETE as workout_locations__id_DELETE } from '../_routes/workout-locations/[id]/route.ts'
import { GET as workout_locations_GET, POST as workout_locations_POST } from '../_routes/workout-locations/route.ts'

export const handle = createRouter('workout-locations', [
  { method: 'PUT', pattern: '/workout-locations/:id', handler: workout_locations__id_PUT },
  { method: 'DELETE', pattern: '/workout-locations/:id', handler: workout_locations__id_DELETE },
  { method: 'GET', pattern: '/workout-locations', handler: workout_locations_GET },
  { method: 'POST', pattern: '/workout-locations', handler: workout_locations_POST },
])
