// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { POST as users__id_reset_password_POST } from '../_routes/users/[id]/reset-password/route.ts'
import { PATCH as users__id_PATCH, DELETE as users__id_DELETE } from '../_routes/users/[id]/route.ts'
import { GET as users_GET, POST as users_POST } from '../_routes/users/route.ts'

export const handle = createRouter('users', [
  { method: 'POST', pattern: '/users/:id/reset-password', handler: users__id_reset_password_POST },
  { method: 'PATCH', pattern: '/users/:id', handler: users__id_PATCH },
  { method: 'DELETE', pattern: '/users/:id', handler: users__id_DELETE },
  { method: 'GET', pattern: '/users', handler: users_GET },
  { method: 'POST', pattern: '/users', handler: users_POST },
])
