// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as export_GET } from '../_routes/export/route.ts'
import { GET as export_zip_GET } from '../_routes/export/zip/route.ts'

export const handle = createRouter('export', [
  { method: 'GET', pattern: '/export', handler: export_GET },
  { method: 'GET', pattern: '/export/zip', handler: export_zip_GET },
])
