// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PATCH as competitions__id_PATCH, DELETE as competitions__id_DELETE } from '../_routes/competitions/[id]/route.ts'
import { GET as competitions_mine_GET } from '../_routes/competitions/mine/route.ts'
import { GET as competitions_GET, POST as competitions_POST } from '../_routes/competitions/route.ts'

export const handle = createRouter('competitions', [
  { method: 'PATCH', pattern: '/competitions/:id', handler: competitions__id_PATCH },
  { method: 'DELETE', pattern: '/competitions/:id', handler: competitions__id_DELETE },
  { method: 'GET', pattern: '/competitions/mine', handler: competitions_mine_GET },
  { method: 'GET', pattern: '/competitions', handler: competitions_GET },
  { method: 'POST', pattern: '/competitions', handler: competitions_POST },
])
