// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as equipment_summary_GET } from '../_routes/equipment-summary/route.ts'

export const handle = createRouter('equipment-summary', [
  { method: 'GET', pattern: '/equipment-summary', handler: equipment_summary_GET },
])
