// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as checks_GET, PATCH as checks_PATCH } from '../_routes/checks/route.ts'

export const handle = createRouter('checks', [
  { method: 'GET', pattern: '/checks', handler: checks_GET },
  { method: 'PATCH', pattern: '/checks', handler: checks_PATCH },
])
