// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as logo_GET, POST as logo_POST, DELETE as logo_DELETE } from '../_routes/logo/route.ts'

export const handle = createRouter('logo', [
  { method: 'GET', pattern: '/logo', handler: logo_GET },
  { method: 'POST', pattern: '/logo', handler: logo_POST },
  { method: 'DELETE', pattern: '/logo', handler: logo_DELETE },
])
