// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { POST as import_competition_corner_apply_POST } from '../_routes/import/competition-corner/apply/route.ts'
import { POST as import_competition_corner_preview_POST } from '../_routes/import/competition-corner/preview/route.ts'
import { POST as import_heats_POST } from '../_routes/import/heats/route.ts'
import { POST as import_judge_assignments_POST } from '../_routes/import/judge-assignments/route.ts'

export const handle = createRouter('import', [
  { method: 'POST', pattern: '/import/competition-corner/apply', handler: import_competition_corner_apply_POST },
  { method: 'POST', pattern: '/import/competition-corner/preview', handler: import_competition_corner_preview_POST },
  { method: 'POST', pattern: '/import/heats', handler: import_heats_POST },
  { method: 'POST', pattern: '/import/judge-assignments', handler: import_judge_assignments_POST },
])
