// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { handle as r_athletes } from '../athletes/routes.ts'
import { handle as r_checks } from '../checks/routes.ts'
import { handle as r_comp_users } from '../comp-users/routes.ts'
import { handle as r_competitions } from '../competitions/routes.ts'
import { handle as r_divisions } from '../divisions/routes.ts'
import { handle as r_equipment_summary } from '../equipment-summary/routes.ts'
import { handle as r_export } from '../export/routes.ts'
import { handle as r_health } from '../health/routes.ts'
import { handle as r_import } from '../import/routes.ts'
import { handle as r_judge_schedule } from '../judge-schedule/routes.ts'
import { handle as r_leaderboard } from '../leaderboard/routes.ts'
import { handle as r_logo } from '../logo/routes.ts'
import { handle as r_me } from '../me/routes.ts'
import { handle as r_ops } from '../ops/routes.ts'
import { handle as r_schedule } from '../schedule/routes.ts'
import { handle as r_settings } from '../settings/routes.ts'
import { handle as r_users } from '../users/routes.ts'
import { handle as r_volunteer_roles } from '../volunteer-roles/routes.ts'
import { handle as r_volunteers } from '../volunteers/routes.ts'
import { handle as r_workout_locations } from '../workout-locations/routes.ts'
import { handle as r_workouts } from '../workouts/routes.ts'

const routers: Record<string, (req: Request) => Promise<Response>> = {
  'athletes': r_athletes,
  'checks': r_checks,
  'comp-users': r_comp_users,
  'competitions': r_competitions,
  'divisions': r_divisions,
  'equipment-summary': r_equipment_summary,
  'export': r_export,
  'health': r_health,
  'import': r_import,
  'judge-schedule': r_judge_schedule,
  'leaderboard': r_leaderboard,
  'logo': r_logo,
  'me': r_me,
  'ops': r_ops,
  'schedule': r_schedule,
  'settings': r_settings,
  'users': r_users,
  'volunteer-roles': r_volunteer_roles,
  'volunteers': r_volunteers,
  'workout-locations': r_workout_locations,
  'workouts': r_workouts,
}

const port = Number(Deno.env.get('PORT') ?? '54321')

Deno.serve({ port }, (req) => {
  const { pathname } = new URL(req.url)
  const segments = pathname.replace(/^\/functions\/v1/, '').split('/')
  const router = routers[segments[1]]
  if (!router) return Promise.resolve(Response.json({ error: 'Not Found' }, { status: 404 }))
  return router(req)
})
