// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as settings_GET, PATCH as settings_PATCH } from '../_routes/settings/route.ts'

export const handle = createRouter('settings', [
  { method: 'GET', pattern: '/settings', handler: settings_GET },
  { method: 'PATCH', pattern: '/settings', handler: settings_PATCH },
])
