// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PUT as volunteer_roles__id_PUT, DELETE as volunteer_roles__id_DELETE } from '../_routes/volunteer-roles/[id]/route.ts'
import { GET as volunteer_roles_GET, POST as volunteer_roles_POST } from '../_routes/volunteer-roles/route.ts'

export const handle = createRouter('volunteer-roles', [
  { method: 'PUT', pattern: '/volunteer-roles/:id', handler: volunteer_roles__id_PUT },
  { method: 'DELETE', pattern: '/volunteer-roles/:id', handler: volunteer_roles__id_DELETE },
  { method: 'GET', pattern: '/volunteer-roles', handler: volunteer_roles_GET },
  { method: 'POST', pattern: '/volunteer-roles', handler: volunteer_roles_POST },
])
