// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as health_GET } from '../_routes/health/route.ts'

export const handle = createRouter('health', [
  { method: 'GET', pattern: '/health', handler: health_GET },
])
