ALTER TABLE "Workout" ADD COLUMN "partBEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Workout" ADD COLUMN "partBScoreType" TEXT NOT NULL DEFAULT 'time';
ALTER TABLE "Score" ADD COLUMN "partBRawScore" DOUBLE PRECISION;
ALTER TABLE "Score" ADD COLUMN "partBPoints" INTEGER;
