// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { PUT as volunteers__id_PUT, DELETE as volunteers__id_DELETE } from '../_routes/volunteers/[id]/route.ts'
import { POST as volunteers__id_swap_POST } from '../_routes/volunteers/[id]/swap/route.ts'
import { GET as volunteers_GET, POST as volunteers_POST, DELETE as volunteers_DELETE } from '../_routes/volunteers/route.ts'

export const handle = createRouter('volunteers', [
  { method: 'PUT', pattern: '/volunteers/:id', handler: volunteers__id_PUT },
  { method: 'DELETE', pattern: '/volunteers/:id', handler: volunteers__id_DELETE },
  { method: 'POST', pattern: '/volunteers/:id/swap', handler: volunteers__id_swap_POST },
  { method: 'GET', pattern: '/volunteers', handler: volunteers_GET },
  { method: 'POST', pattern: '/volunteers', handler: volunteers_POST },
  { method: 'DELETE', pattern: '/volunteers', handler: volunteers_DELETE },
])
