// Generated by tools/gen-functions.mjs. Run pnpm gen:functions after adding a route.
import { createRouter } from '../_shared/router.ts'
import { GET as judge_schedule_GET } from '../_routes/judge-schedule/route.ts'

export const handle = createRouter('judge-schedule', [
  { method: 'GET', pattern: '/judge-schedule', handler: judge_schedule_GET },
])
